server:
  port: 10202
spring:
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/mongo_test?minPoolSize=3000&maxPoolSize=3000&maxIdleTimeMS=60000&waitQueueMultiple=10&waitQueueTimeoutMS=60000
      uuid-representation: standard