
server:
  port: 10201
#  tomcat:
#    threads:
#      max: 3000

spring:
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/mongo_test?minPoolSize=200&maxPoolSize=200&maxIdleTimeMS=60000&waitQueueMultiple=10&waitQueueTimeoutMS=60000
      uuid-representation: standard
